// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateGroupRes interface {
	createGroupRes()
}

type CreateUserRes interface {
	createUserRes()
}

type CreateVideoRes interface {
	createVideoRes()
}

type DeleteGroupRes interface {
	deleteGroupRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type DeleteVideoRes interface {
	deleteVideoRes()
}

type ListGroupAdminsRes interface {
	listGroupAdminsRes()
}

type ListGroupMembersRes interface {
	listGroupMembersRes()
}

type ListGroupModeratorsRes interface {
	listGroupModeratorsRes()
}

type ListGroupRes interface {
	listGroupRes()
}

type ListGroupStreamersRes interface {
	listGroupStreamersRes()
}

type ListGroupVideosRes interface {
	listGroupVideosRes()
}

type ListUserAdminGroupsRes interface {
	listUserAdminGroupsRes()
}

type ListUserJoinedGroupsRes interface {
	listUserJoinedGroupsRes()
}

type ListUserLikedVideosRes interface {
	listUserLikedVideosRes()
}

type ListUserModeratedVideosRes interface {
	listUserModeratedVideosRes()
}

type ListUserModeratingGroupsRes interface {
	listUserModeratingGroupsRes()
}

type ListUserRes interface {
	listUserRes()
}

type ListUserStreamVideosRes interface {
	listUserStreamVideosRes()
}

type ListUserStreamingGroupsRes interface {
	listUserStreamingGroupsRes()
}

type ListUserViewedVideosRes interface {
	listUserViewedVideosRes()
}

type ListVideoLikesRes interface {
	listVideoLikesRes()
}

type ListVideoModeratersRes interface {
	listVideoModeratersRes()
}

type ListVideoRes interface {
	listVideoRes()
}

type ListVideoStreamersRes interface {
	listVideoStreamersRes()
}

type ListVideoViewersRes interface {
	listVideoViewersRes()
}

type ReadGroupRes interface {
	readGroupRes()
}

type ReadUserRes interface {
	readUserRes()
}

type ReadVideoGroupRes interface {
	readVideoGroupRes()
}

type ReadVideoRes interface {
	readVideoRes()
}

type UpdateGroupRes interface {
	updateGroupRes()
}

type UpdateUserRes interface {
	updateUserRes()
}

type UpdateVideoRes interface {
	updateVideoRes()
}
