// Code generated by entc, DO NOT EDIT.

package entgen

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"example.com/enumeg/entgen/group"
)

// Group is the model entity for the Group schema.
type Group struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Thumbnail holds the value of the "thumbnail" field.
	Thumbnail string `json:"thumbnail,omitempty"`
	// Views holds the value of the "views" field.
	Views int `json:"views,omitempty"`
	// Subscribers holds the value of the "subscribers" field.
	Subscribers int `json:"subscribers,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupQuery when eager-loading is set.
	Edges GroupEdges `json:"edges"`
}

// GroupEdges holds the relations/edges for other nodes in the graph.
type GroupEdges struct {
	// Admins holds the value of the admins edge.
	Admins []*User `json:"admins,omitempty"`
	// Members holds the value of the members edge.
	Members []*User `json:"members,omitempty"`
	// Videos holds the value of the videos edge.
	Videos []*Video `json:"videos,omitempty"`
	// Moderators holds the value of the moderators edge.
	Moderators []*User `json:"moderators,omitempty"`
	// Streamers holds the value of the streamers edge.
	Streamers []*User `json:"streamers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// AdminsOrErr returns the Admins value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) AdminsOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Admins, nil
	}
	return nil, &NotLoadedError{edge: "admins"}
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) MembersOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// VideosOrErr returns the Videos value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) VideosOrErr() ([]*Video, error) {
	if e.loadedTypes[2] {
		return e.Videos, nil
	}
	return nil, &NotLoadedError{edge: "videos"}
}

// ModeratorsOrErr returns the Moderators value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) ModeratorsOrErr() ([]*User, error) {
	if e.loadedTypes[3] {
		return e.Moderators, nil
	}
	return nil, &NotLoadedError{edge: "moderators"}
}

// StreamersOrErr returns the Streamers value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) StreamersOrErr() ([]*User, error) {
	if e.loadedTypes[4] {
		return e.Streamers, nil
	}
	return nil, &NotLoadedError{edge: "streamers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Group) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case group.FieldID, group.FieldViews, group.FieldSubscribers:
			values[i] = new(sql.NullInt64)
		case group.FieldName, group.FieldDescription, group.FieldURL, group.FieldThumbnail:
			values[i] = new(sql.NullString)
		case group.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Group", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Group fields.
func (gr *Group) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case group.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			gr.ID = int(value.Int64)
		case group.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				gr.Name = value.String
			}
		case group.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				gr.Description = value.String
			}
		case group.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				gr.URL = value.String
			}
		case group.FieldThumbnail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail", values[i])
			} else if value.Valid {
				gr.Thumbnail = value.String
			}
		case group.FieldViews:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field views", values[i])
			} else if value.Valid {
				gr.Views = int(value.Int64)
			}
		case group.FieldSubscribers:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscribers", values[i])
			} else if value.Valid {
				gr.Subscribers = int(value.Int64)
			}
		case group.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				gr.CreatedAt = value.Time
			}
		}
	}
	return nil
}

// QueryAdmins queries the "admins" edge of the Group entity.
func (gr *Group) QueryAdmins() *UserQuery {
	return (&GroupClient{config: gr.config}).QueryAdmins(gr)
}

// QueryMembers queries the "members" edge of the Group entity.
func (gr *Group) QueryMembers() *UserQuery {
	return (&GroupClient{config: gr.config}).QueryMembers(gr)
}

// QueryVideos queries the "videos" edge of the Group entity.
func (gr *Group) QueryVideos() *VideoQuery {
	return (&GroupClient{config: gr.config}).QueryVideos(gr)
}

// QueryModerators queries the "moderators" edge of the Group entity.
func (gr *Group) QueryModerators() *UserQuery {
	return (&GroupClient{config: gr.config}).QueryModerators(gr)
}

// QueryStreamers queries the "streamers" edge of the Group entity.
func (gr *Group) QueryStreamers() *UserQuery {
	return (&GroupClient{config: gr.config}).QueryStreamers(gr)
}

// Update returns a builder for updating this Group.
// Note that you need to call Group.Unwrap() before calling this method if this Group
// was returned from a transaction, and the transaction was committed or rolled back.
func (gr *Group) Update() *GroupUpdateOne {
	return (&GroupClient{config: gr.config}).UpdateOne(gr)
}

// Unwrap unwraps the Group entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (gr *Group) Unwrap() *Group {
	tx, ok := gr.config.driver.(*txDriver)
	if !ok {
		panic("entgen: Group is not a transactional entity")
	}
	gr.config.driver = tx.drv
	return gr
}

// String implements the fmt.Stringer.
func (gr *Group) String() string {
	var builder strings.Builder
	builder.WriteString("Group(")
	builder.WriteString(fmt.Sprintf("id=%v", gr.ID))
	builder.WriteString(", name=")
	builder.WriteString(gr.Name)
	builder.WriteString(", description=")
	builder.WriteString(gr.Description)
	builder.WriteString(", url=")
	builder.WriteString(gr.URL)
	builder.WriteString(", thumbnail=")
	builder.WriteString(gr.Thumbnail)
	builder.WriteString(", views=")
	builder.WriteString(fmt.Sprintf("%v", gr.Views))
	builder.WriteString(", subscribers=")
	builder.WriteString(fmt.Sprintf("%v", gr.Subscribers))
	builder.WriteString(", created_at=")
	builder.WriteString(gr.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Groups is a parsable slice of Group.
type Groups []*Group

func (gr Groups) config(cfg config) {
	for _i := range gr {
		gr[_i].config = cfg
	}
}
